//Ventana de Inicio
package torrehanoi;


public class VentanaInicio extends javax.swing.JFrame {

    
    public VentanaInicio() {
        initComponents();
        this.setLocationRelativeTo(this);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelTorresDeHanoi = new javax.swing.JLabel();
        nuevoJuego = new javax.swing.JButton();
        juegoAutomatico = new javax.swing.JButton();
        top5 = new javax.swing.JButton();
        configuracion = new javax.swing.JButton();
        salirInicio = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelTorresDeHanoi.setFont(new java.awt.Font("Caladea", 1, 48)); // NOI18N
        labelTorresDeHanoi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTorresDeHanoi.setText("TORRES DE HANOI");
        jPanel1.add(labelTorresDeHanoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 57, 1000, -1));

        nuevoJuego.setBackground(new java.awt.Color(255, 153, 51));
        nuevoJuego.setFont(new java.awt.Font("P052", 3, 24)); // NOI18N
        nuevoJuego.setText("Nuevo Juego");
        nuevoJuego.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        nuevoJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoJuegoActionPerformed(evt);
            }
        });
        jPanel1.add(nuevoJuego, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, 340, -1));

        juegoAutomatico.setBackground(new java.awt.Color(255, 255, 102));
        juegoAutomatico.setFont(new java.awt.Font("P052", 3, 24)); // NOI18N
        juegoAutomatico.setText("Juego Automatico");
        juegoAutomatico.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        juegoAutomatico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                juegoAutomaticoActionPerformed(evt);
            }
        });
        jPanel1.add(juegoAutomatico, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, 340, -1));

        top5.setBackground(new java.awt.Color(102, 255, 102));
        top5.setFont(new java.awt.Font("P052", 3, 24)); // NOI18N
        top5.setText("Top 5");
        top5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        top5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                top5ActionPerformed(evt);
            }
        });
        jPanel1.add(top5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 390, 340, -1));

        configuracion.setBackground(new java.awt.Color(0, 153, 153));
        configuracion.setFont(new java.awt.Font("P052", 3, 24)); // NOI18N
        configuracion.setText("Configuración");
        configuracion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        configuracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                configuracionActionPerformed(evt);
            }
        });
        jPanel1.add(configuracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 470, 340, -1));

        salirInicio.setBackground(new java.awt.Color(255, 51, 51));
        salirInicio.setFont(new java.awt.Font("Comfortaa", 1, 24)); // NOI18N
        salirInicio.setForeground(new java.awt.Color(255, 255, 255));
        salirInicio.setText("Salir");
        salirInicio.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        salirInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirInicioActionPerformed(evt);
            }
        });
        jPanel1.add(salirInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 530, 120, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Rainbow-colors-wood-board-background_1024x768.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void top5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_top5ActionPerformed
        this.setVisible(false);
        TorreHanoi.topJugadores.setVisible(true);
    }//GEN-LAST:event_top5ActionPerformed

    public static void LlenarMatriz (){
        int total = Integer.parseInt(TorreHanoi.config.discos);//Integer.valueOf(TorreHanoi.config.discos);
        
        for (int i = TorreHanoi.matrizJuego.length -1; i >= 0; i--) { //Llenado de Matrices
            for (int j = 0; j < TorreHanoi.matrizJuego[0].length; j++) {
                TorreHanoi.matrizJuego [i][j] = 0; //Llenando matriz de juego
                TorreHanoi.matrizFinal [i][j] = 0; //Llenando la matriz final
            }
            if (total > 0){
                //Se coloca el valor del total de discos en la primera columna de la matriz del juego y en la última columna de la matriz final
                TorreHanoi.matrizJuego [i][0] = total;
                TorreHanoi.matrizFinal [i][2] = total;
                total--;
            }
        }
        
    }
    
    private void nuevoJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoJuegoActionPerformed
        this.setVisible(false);
        LlenarMatriz(); //Al presionar que llene la matriz del juego y la matriz objetivo
        TorreHanoi.juego.Bloques(); //Para colocar los bloques que se utilizarán en el juego
        TorreHanoi.juego.movimientos = 0; //Conteo de movimientos en cero
        TorreHanoi.juego.setVisible(true);
        TorreHanoi.juego.reloj.start(); //Que inicie el conteo del tiempo
        TorreHanoi.juego.labelTiempo.setText(TorreHanoi.config.segConfig); //Que coloque el tiempo inicial en el label
        TorreHanoi.juego.labelMovimientos.setText(String.valueOf(TorreHanoi.juego.movimientos)); //Que coloque los movimientos iniciales
        TorreHanoi.juego.segundos = Integer.valueOf(TorreHanoi.config.segConfig); //Segundos del juego
    }//GEN-LAST:event_nuevoJuegoActionPerformed

    private void juegoAutomaticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_juegoAutomaticoActionPerformed
        this.setVisible(false);
        TorreHanoi.juegoAutomatico.labelDiscos.setText(TorreHanoi.config.discos); //Configura la cantidad de discos iniciales según la configuración
        TorreHanoi.juegoAutomatico.labelMovimientos.setText("0"); //Inicia en cero movimientos
        TorreHanoi.juegoAutomatico.setVisible(true);
    }//GEN-LAST:event_juegoAutomaticoActionPerformed

    private void salirInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirInicioActionPerformed
        System.exit(0); //Cerrar el programa al presionar el boton de salir
    }//GEN-LAST:event_salirInicioActionPerformed

    private void configuracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_configuracionActionPerformed
        this.setVisible(false);
        TorreHanoi.config.setVisible(true);
    }//GEN-LAST:event_configuracionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton configuracion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton juegoAutomatico;
    private javax.swing.JLabel labelTorresDeHanoi;
    private javax.swing.JButton nuevoJuego;
    private javax.swing.JButton salirInicio;
    private javax.swing.JButton top5;
    // End of variables declaration//GEN-END:variables
}
