//Ventana del top 5 de mejores jugadores
package torrehanoi;

import javax.swing.JLabel;

/**
 *
 * @author fredyquijada
 */
public class VentanaTopJugadores extends javax.swing.JFrame {

    /**
     * Creates new form VentanaTopJugadores
     */
    public VentanaTopJugadores() {
        initComponents();
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtTiempo1 = new javax.swing.JLabel();
        txtMovimientos1 = new javax.swing.JLabel();
        txtDiscos1 = new javax.swing.JLabel();
        txtNombre1 = new javax.swing.JLabel();
        txtTiempo2 = new javax.swing.JLabel();
        txtMovimientos2 = new javax.swing.JLabel();
        txtDiscos2 = new javax.swing.JLabel();
        txtNombre2 = new javax.swing.JLabel();
        txtTiempo3 = new javax.swing.JLabel();
        txtMovimientos3 = new javax.swing.JLabel();
        txtDiscos3 = new javax.swing.JLabel();
        txtNombre3 = new javax.swing.JLabel();
        txtTiempo4 = new javax.swing.JLabel();
        txtMovimientos4 = new javax.swing.JLabel();
        txtDiscos4 = new javax.swing.JLabel();
        txtNombre4 = new javax.swing.JLabel();
        txtTiempo5 = new javax.swing.JLabel();
        txtMovimientos5 = new javax.swing.JLabel();
        txtDiscos5 = new javax.swing.JLabel();
        txtNombre5 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("P052", 1, 18)); // NOI18N
        jLabel16.setText("Tiempo");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 130, 120, -1));

        jLabel1.setFont(new java.awt.Font("P052", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Mejores Jugadores");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 1000, -1));

        jLabel2.setFont(new java.awt.Font("P052", 1, 24)); // NOI18N
        jLabel2.setText("Quinto Lugar:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, 200, -1));

        jLabel3.setFont(new java.awt.Font("P052", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("             Nombre                          Discos          Movimientos");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 630, 30));

        jLabel4.setFont(new java.awt.Font("P052", 1, 18)); // NOI18N
        jLabel4.setText("Sobrante");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 150, 120, -1));

        jLabel5.setText("           -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, 990, -1));

        jLabel6.setText("           -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 100, 990, -1));

        jLabel7.setFont(new java.awt.Font("P052", 1, 24)); // NOI18N
        jLabel7.setText("Primer Lugar:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 200, -1));

        jLabel8.setFont(new java.awt.Font("P052", 1, 24)); // NOI18N
        jLabel8.setText("Segundo Lugar:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 200, -1));

        jLabel9.setFont(new java.awt.Font("P052", 1, 24)); // NOI18N
        jLabel9.setText("Tercer Lugar:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 200, -1));

        jLabel10.setFont(new java.awt.Font("P052", 1, 24)); // NOI18N
        jLabel10.setText("Cuarto Lugar:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 200, -1));

        jLabel11.setText("           -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 990, -1));

        jLabel12.setText("           -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 990, -1));

        jLabel13.setText("           -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 990, -1));

        jLabel14.setText("           -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 990, -1));

        jLabel15.setText("           -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 990, -1));

        jButton1.setBackground(new java.awt.Color(102, 255, 102));
        jButton1.setFont(new java.awt.Font("P052", 1, 24)); // NOI18N
        jButton1.setText("Regresar");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 540, 350, -1));

        txtTiempo1.setFont(new java.awt.Font("P052", 1, 18)); // NOI18N
        txtTiempo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(txtTiempo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 200, 200, 30));

        txtMovimientos1.setFont(new java.awt.Font("P052", 1, 18)); // NOI18N
        txtMovimientos1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(txtMovimientos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 200, 200, 30));

        txtDiscos1.setFont(new java.awt.Font("P052", 1, 18)); // NOI18N
        txtDiscos1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(txtDiscos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, 200, 30));

        txtNombre1.setFont(new java.awt.Font("P052", 1, 18)); // NOI18N
        txtNombre1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(txtNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 310, 30));

        txtTiempo2.setFont(new java.awt.Font("P052", 1, 18)); // NOI18N
        txtTiempo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(txtTiempo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 270, 200, 30));

        txtMovimientos2.setFont(new java.awt.Font("P052", 1, 18)); // NOI18N
        txtMovimientos2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(txtMovimientos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 270, 200, 30));

        txtDiscos2.setFont(new java.awt.Font("P052", 1, 18)); // NOI18N
        txtDiscos2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(txtDiscos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 270, 200, 30));

        txtNombre2.setFont(new java.awt.Font("P052", 1, 18)); // NOI18N
        txtNombre2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(txtNombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 310, 30));

        txtTiempo3.setFont(new java.awt.Font("P052", 1, 18)); // NOI18N
        txtTiempo3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(txtTiempo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 340, 200, 30));

        txtMovimientos3.setFont(new java.awt.Font("P052", 1, 18)); // NOI18N
        txtMovimientos3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(txtMovimientos3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 340, 200, 30));

        txtDiscos3.setFont(new java.awt.Font("P052", 1, 18)); // NOI18N
        txtDiscos3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(txtDiscos3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 340, 200, 30));

        txtNombre3.setFont(new java.awt.Font("P052", 1, 18)); // NOI18N
        txtNombre3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(txtNombre3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, 310, 30));

        txtTiempo4.setFont(new java.awt.Font("P052", 1, 18)); // NOI18N
        txtTiempo4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(txtTiempo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 410, 200, 30));

        txtMovimientos4.setFont(new java.awt.Font("P052", 1, 18)); // NOI18N
        txtMovimientos4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(txtMovimientos4, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 410, 200, 30));

        txtDiscos4.setFont(new java.awt.Font("P052", 1, 18)); // NOI18N
        txtDiscos4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(txtDiscos4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 410, 200, 30));

        txtNombre4.setFont(new java.awt.Font("P052", 1, 18)); // NOI18N
        txtNombre4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(txtNombre4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 410, 310, 30));

        txtTiempo5.setFont(new java.awt.Font("P052", 1, 18)); // NOI18N
        txtTiempo5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(txtTiempo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 470, 200, 30));

        txtMovimientos5.setFont(new java.awt.Font("P052", 1, 18)); // NOI18N
        txtMovimientos5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(txtMovimientos5, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 470, 200, 30));

        txtDiscos5.setFont(new java.awt.Font("P052", 1, 18)); // NOI18N
        txtDiscos5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(txtDiscos5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 470, 200, 30));

        txtNombre5.setFont(new java.awt.Font("P052", 1, 18)); // NOI18N
        txtNombre5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(txtNombre5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 470, 310, 30));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondocolores.jpg"))); // NOI18N
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        TorreHanoi.menu.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaTopJugadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaTopJugadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaTopJugadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaTopJugadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaTopJugadores().setVisible(true);
            }
        });
    }

    public void setTxtDiscos1(JLabel txtDiscos1) {
        this.txtDiscos1 = txtDiscos1;
    }

    public void setTxtDiscos2(JLabel txtDiscos2) {
        this.txtDiscos2 = txtDiscos2;
    }

    public void setTxtDiscos3(JLabel txtDiscos3) {
        this.txtDiscos3 = txtDiscos3;
    }

    public void setTxtDiscos4(JLabel txtDiscos4) {
        this.txtDiscos4 = txtDiscos4;
    }

    public void setTxtDiscos5(JLabel txtDiscos5) {
        this.txtDiscos5 = txtDiscos5;
    }

    public void setTxtMovimientos1(JLabel txtMovimientos1) {
        this.txtMovimientos1 = txtMovimientos1;
    }

    public void setTxtMovimientos2(JLabel txtMovimientos2) {
        this.txtMovimientos2 = txtMovimientos2;
    }

    public void setTxtMovimientos3(JLabel txtMovimientos3) {
        this.txtMovimientos3 = txtMovimientos3;
    }

    public void setTxtMovimientos4(JLabel txtMovimientos4) {
        this.txtMovimientos4 = txtMovimientos4;
    }

    public void setTxtMovimientos5(JLabel txtMovimientos5) {
        this.txtMovimientos5 = txtMovimientos5;
    }

    public void setTxtNombre1(JLabel txtNombre1) {
        this.txtNombre1 = txtNombre1;
    }

    public void setTxtNombre2(JLabel txtNombre2) {
        this.txtNombre2 = txtNombre2;
    }

    public void setTxtNombre3(JLabel txtNombre3) {
        this.txtNombre3 = txtNombre3;
    }

    public void setTxtNombre4(JLabel txtNombre4) {
        this.txtNombre4 = txtNombre4;
    }

    public void setTxtNombre5(JLabel txtNombre5) {
        this.txtNombre5 = txtNombre5;
    }

    public void setTxtTiempo1(JLabel txtTiempo1) {
        this.txtTiempo1 = txtTiempo1;
    }

    public void setTxtTiempo2(JLabel txtTiempo2) {
        this.txtTiempo2 = txtTiempo2;
    }

    public void setTxtTiempo3(JLabel txtTiempo3) {
        this.txtTiempo3 = txtTiempo3;
    }

    public void setTxtTiempo4(JLabel txtTiempo4) {
        this.txtTiempo4 = txtTiempo4;
    }

    public void setTxtTiempo5(JLabel txtTiempo5) {
        this.txtTiempo5 = txtTiempo5;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JLabel txtDiscos1;
    public static javax.swing.JLabel txtDiscos2;
    public static javax.swing.JLabel txtDiscos3;
    public static javax.swing.JLabel txtDiscos4;
    public static javax.swing.JLabel txtDiscos5;
    public static javax.swing.JLabel txtMovimientos1;
    public static javax.swing.JLabel txtMovimientos2;
    public static javax.swing.JLabel txtMovimientos3;
    public static javax.swing.JLabel txtMovimientos4;
    public static javax.swing.JLabel txtMovimientos5;
    public static javax.swing.JLabel txtNombre1;
    public static javax.swing.JLabel txtNombre2;
    public static javax.swing.JLabel txtNombre3;
    public static javax.swing.JLabel txtNombre4;
    public static javax.swing.JLabel txtNombre5;
    public static javax.swing.JLabel txtTiempo1;
    public static javax.swing.JLabel txtTiempo2;
    public static javax.swing.JLabel txtTiempo3;
    public static javax.swing.JLabel txtTiempo4;
    public static javax.swing.JLabel txtTiempo5;
    // End of variables declaration//GEN-END:variables
}
