//Ventana del top 5 de mejores jugadores
package torrehanoi;

import javax.swing.JLabel;

/**
 *
 * @author fredyquijada
 */
public class VentanaJuegoAutomatico extends javax.swing.JFrame {
    
    int movimientos = 0;
    String texto = "";
    
    public VentanaJuegoAutomatico() {
        initComponents();
        this.setLocationRelativeTo(this);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        labelDiscos = new javax.swing.JLabel();
        labelMovimientos = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        pantallaMovimientos = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("P052", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Juego Automático");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1000, -1));

        jLabel2.setFont(new java.awt.Font("P052", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Discos");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 150, -1));

        jLabel3.setFont(new java.awt.Font("P052", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Movimientos");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 230, -1));

        labelDiscos.setFont(new java.awt.Font("P052", 1, 24)); // NOI18N
        labelDiscos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelDiscos.setText("3");
        jPanel1.add(labelDiscos, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 150, -1));

        labelMovimientos.setFont(new java.awt.Font("P052", 1, 24)); // NOI18N
        labelMovimientos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMovimientos.setText("0");
        jPanel1.add(labelMovimientos, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 150, -1));

        pantallaMovimientos.setEditable(false);
        pantallaMovimientos.setColumns(20);
        pantallaMovimientos.setRows(5);
        jScrollPane2.setViewportView(pantallaMovimientos);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 840, 220));

        jButton1.setBackground(new java.awt.Color(102, 255, 102));
        jButton1.setFont(new java.awt.Font("P052", 1, 18)); // NOI18N
        jButton1.setText("Iniciar");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 520, 170, 40));

        jButton2.setBackground(new java.awt.Color(153, 204, 255));
        jButton2.setFont(new java.awt.Font("P052", 1, 18)); // NOI18N
        jButton2.setText("Regresar");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 520, 170, 40));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondocolores.jpg"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.pantallaMovimientos.setText("");
        this.setVisible(false);
        TorreHanoi.menu.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        movimientos = 0;
        this.pantallaMovimientos.setText("");
        ResolucionAutomatica(Integer.valueOf(TorreHanoi.config.discos), 1, 2, 3);
        this.pantallaMovimientos.setText(this.pantallaMovimientos.getText() + "Se terminó el juego con " + movimientos + " movimientos");
    }//GEN-LAST:event_jButton1ActionPerformed
    
    public void ResolucionAutomatica (int discos, int torre1, int torre2, int torre3){
        if (discos == 1){
            this.pantallaMovimientos.setText(this.pantallaMovimientos.getText() + "Se movió el disco #" + discos + " de la torre #" + torre1 + " a la torre #" + torre3 + "\n\n");
            movimientos ++;
            this.labelMovimientos.setText(String.valueOf(movimientos));
        } else {
            ResolucionAutomatica(discos - 1, torre1, torre3, torre2);
            this.pantallaMovimientos.setText(this.pantallaMovimientos.getText() + "Se movió el disco #" + discos + " de la torre #" + torre1 + " a la torre #" + torre3 + "\n\n");
            movimientos ++;
            this.labelMovimientos.setText(String.valueOf(movimientos));
            ResolucionAutomatica(discos -1, torre2, torre1, torre3);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaJuegoAutomatico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaJuegoAutomatico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaJuegoAutomatico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaJuegoAutomatico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaJuegoAutomatico().setVisible(true);
            }
        });
    }

    public void setLabelDiscos(JLabel labelDiscos) {
        this.labelDiscos = labelDiscos;
    }

    public void setLabelMovimientos(JLabel labelMovimientos) {
        this.labelMovimientos = labelMovimientos;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JLabel labelDiscos;
    public static javax.swing.JLabel labelMovimientos;
    public static javax.swing.JTextArea pantallaMovimientos;
    // End of variables declaration//GEN-END:variables
}
